---

- name: DataSploit | Clone git repo
  git:
    repo: https://github.com/DataSploit/datasploit.git
    dest: /opt/DataSploit
    clone: yes
    force: yes
    depth: 1

- name: DataSploit | Install pip requirements
  pip:
    requirements: /opt/DataSploit/requirements.txt
    state: present
